#### --- GENERATED --- ####

libavcodec_vulkan_optional_sources = {
  'dpx_vulkan_hwaccel' : files('dpx_unpack.comp.glsl','dpx_copy.comp.glsl'),
  'ffv1_vulkan_encoder' : files('ffv1_enc_setup.comp.glsl','ffv1_enc_reset.comp.glsl','ffv1_enc_reset_golomb.comp.glsl','ffv1_enc.comp.glsl','ffv1_enc_golomb.comp.glsl','ffv1_enc_rgb.comp.glsl','ffv1_enc_rgb_golomb.comp.glsl','ffv1_enc_rct_search.comp.glsl'),
  'ffv1_vulkan_hwaccel' : files('ffv1_dec_setup.comp.glsl','ffv1_dec_reset.comp.glsl','ffv1_dec_reset_golomb.comp.glsl','ffv1_dec.comp.glsl','ffv1_dec_golomb.comp.glsl','ffv1_dec_rgb.comp.glsl','ffv1_dec_rgb_golomb.comp.glsl'),
  'prores_ks_vulkan_encoder' : files('prores_ks_alpha_data.comp.glsl','prores_ks_slice_data.comp.glsl','prores_ks_estimate_slice.comp.glsl','prores_ks_encode_slice.comp.glsl','prores_ks_trellis_node.comp.glsl'),
  'prores_raw_vulkan_hwaccel' : files('prores_raw_decode.comp.glsl','prores_raw_idct.comp.glsl'),
  'prores_vulkan_hwaccel' : files('prores_vld.comp.glsl','prores_idct.comp.glsl'),
}

#### --- END GENERATED --- ####
